# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

files: ^spalah|tests|.github
exclude: 'docs'
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-docstring-first
      - id: debug-statements
      - id: check-yaml
      - id: check-ast
      - id: flake8
        args: # arguments to configure flake8        
        - "--max-line-length=100"
  - repo: https://github.com/ambv/black
    rev: 22.3.0 
    hooks:
      - id: black
        args: [--line-length=100]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
      - id: mypy
        additional_dependencies: [types-PyYAML]
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.19.4
    hooks:
      - id: pyupgrade
        name: Check for code that can use new Python features
        args: [--py37-plus]
  
