name: spalah docs

on: 
  push:
    branches:
      - main
    paths:
      - "spalah/**"
      - "docs/**"
      - "mkdocs.yml"
  workflow_dispatch:


concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  precommit:
    name: Build docs
    runs-on: ubuntu-latest
    env:
      working-directory: .

    steps:
      - uses: actions/checkout@v3

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - uses: actions/setup-python@v3
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: uv sync --group docs; uv pip install -e .

      - name: Prepare branch gh-pages
        if: ${{false}}
        run: |
          git branch -D gh-pages || true
          git checkout -t upstream/gh-pages # (change upstream to your actual remote)
          git checkout main

      - name: Build docs and publish to a dedicated branch
        run: uv run mkdocs gh-deploy --force
        working-directory: ${{env.working-directory}}
