name: spalah CI

on:
  pull_request:
    paths:
      - "spalah/**"
      - "tests/**"
      - ".github/workflows/spalah_ci.yaml"

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  precommit:
    name: CI
    runs-on: ubuntu-latest
    env:
      working-directory: .

    steps:
      - uses: actions/checkout@v3

      - name: Install poetry
        run: pipx install poetry

      - uses: actions/setup-python@v3
        with:
          python-version: '3.8'
          cache: 'poetry'

      - name: Install Dependencies
        run: poetry install --with dev


      - name: Install spalah dependencies
        run: poetry install
        working-directory: ${{env.working-directory}}

      - uses: pre-commit/action@v2.0.0
        with:
          extra_args: --all

      - name: Test spalah package
        run: poetry run pytest --cache-clear --cov=spalah tests/ > pytest-coverage.txt

      - name: Comment coverage
        uses: coroo/pytest-coverage-commentator@v1.0.2
