name: spalah CI

on:
  pull_request:
    paths:
      - "spalah/**"
      - "docs/**"
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  precommit:
    name: Build docs
    runs-on: ubuntu-latest
    env:
      working-directory: .

    steps:
      - uses: actions/checkout@v3

      - name: Install poetry
        run: pipx install poetry

      - uses: actions/setup-python@v3
        with:
          python-version: '3.8'
          cache: 'poetry'

      - name: Install Dependencies
        run: poetry install --with docs

      - name: Build docs and publish to a dedicated branch
        run: poetry run mkdocs gh-deploy
        working-directory: ${{env.working-directory}}

