name: spalah CI

on:
  pull_request:
    paths:
      - "spalah/**"
      - "tests/**"
      - ".github/workflows/**"

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  precommit:
    name: CI
    runs-on: ubuntu-latest
    env:
      working-directory: .
      PYTHON_VERSION: 3.8
      POETRY_VERSION: 1.3.2
      POETRY_URL: https://install.python-poetry.org

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Cache Poetry cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry
          key: poetry-cache-${{ runner.os }}-${{ env.PYTHON_VERSION }}-${{ env.POETRY_VERSION }}
      # virtualenv cache should depends on OS, Python version and `poetry.lock` (and optionally workflow files).

      - name: Cache Packages
        uses: actions/cache@v3
        with:
          path: ~/.local
          key: poetry-${{ runner.os }}-${{ env.PYTHON_VERSION }}-${{ hashFiles('**/poetry.lock') }}-${{ hashFiles('.github/workflows/*.yml') }}

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install Poetry
        run: |
          curl -sSL ${{ env.POETRY_URL }} | python - --version ${{ env.POETRY_VERSION }}
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install Dependencies
        run: poetry install
      # Write actual actions here.


      - name: Get the list of changed files
        id: get_list_of_files
        run:  |
          git fetch origin main:refs/remotes/origin/main
          FILES_CHANGED=$(git diff --name-only origin/main)

          echo "Changed files:"
          echo "$FILES_CHANGED"

          echo "PR_FILES_CHANGED=$( echo $FILES_CHANGED | tr '\n' ' ')" >> $GITHUB_ENV

      - name: Install spalah dependencies
        run: poetry install
        working-directory: ${{env.working-directory}}

      - uses: pre-commit/action@v2.0.0
        with:
          extra_args: --files ${{ env.PR_FILES_CHANGED }}

      - name: Test spalah package
        run: poetry run pytest --cache-clear --cov=spalah tests/ > pytest-coverage.txt

      - name: Comment coverage
        uses: coroo/pytest-coverage-commentator@v1.0.2
